### ISSUE TITLE
No Deneb payload

### ISSUE THREAD

**Issue by halo3mic** [flashbots/suave-geth#176]
When submitting the block to the relay via Suave I get bad request with error `{"code":400,"message":"not deneb payload"}\n`.

The source of the error is [here in the relay code](https://github.com/flashbots/mev-boost-relay/blob/d2237f875f60363959db03b5114141fa16a685b2/services/api/service.go#L1648-L1653).

It appears suave-geth and suave-execution-geth need support for [the new payload](https://github.com/flashbots/builder/blob/677a32d6ea01d1500458d594ff6c7d41b2b315c9/builder/builder.go#L637-L671) with blobs.

**Comment by lthibault** [comment]
@halo3mic Are you sending SSZ or JSON encoded payloads?  Can you provide an example payload so that we can reproduce?

**Comment by lthibault** [comment]
@halo3mic Okay, I think I've narrowed it down a bit.  Any chance you'd be willing to take over and submit a PR? 😃 

I believe the issue is in `buildEthBlock`, [here](https://github.com/flashbots/suave-geth/blob/main/core/vm/contracts_suave_eth.go#L262-L266).  Notice that it's building a Capella block submission request.  Presumably that should be a Deneb variant.  I believe the `attestantio/go-builder/client` library may need a version bump.

Wanna give it a shot?

**Comment by lthibault** [comment]
Per conversation on Telegram, #188 has not resolved the issue.

**Comment by lthibault** [comment]
I suspect the issue might be [here](https://github.com/flashbots/suave-geth/blob/main/miner/worker.go#L1298). The `beaconRoot` is not included as part of the block (see equivalent here in the [normal builder](https://github.com/flashbots/builder/blob/deneb/miner/worker.go#L1118)).

There are actually are three new fields introduced by Deneb:

- `ParentBeaconRoot `
- `ExcessBlobGas`
- `BlobGasUsed`

**Comment by lthibault** [comment]
Okay, I think the beacon root needs to be set, as `beaconRoot` is part of the [`Header` struct](https://github.com/flashbots/builder/blob/deneb/core/types/block.go#L95) when calculating the block hash.
